fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\FOSUser
    from_email:
        address: "SymfonyCinema@gmail.com"
        sender_name: "CinemaCity"