fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\FOSUser
    from_email:
        address: ymfonyCinema@gmail.com
        sender_name: CinemaCity
    use_listener: false
    
    registration:
        confirmation:
            from_email:
                address: ymfonyCinema@gmail.com
                sender_name: CinemaCity
            enabled: true
    
    resetting:
        email:
            from_email:
                address: ymfonyCinema@gmail.com
                sender_name: CinemaCity