fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\FOSUser
    from_email:
        address: ymfonyCinema@gmail.com
        sender_name: CinemaCity
    use_listener: false
    
    registration:
        confirmation:
            from_email:
                address: ymfonyCinema@gmail.com
                sender_name: CinemaCity
            enabled: true
        form:
            type: App\Form\RegistrationFormType
    
    resetting:
        email:
            from_email:
                address: ymfonyCinema@gmail.com
                sender_name: CinemaCity
        form:
            type: App\Form\ResettingFormType
    profile:
        form:
            type: App\Form\ProfileFormType
    change_password:
        form:
            type: App\Form\ChangePasswordFormType
        
    
        